task 1


In [ ]:
#list
a=[7,2025,'tiger','lion']
print(a)
print(len(a))

[7, 2025, 'tiger', 'lion']
4


In [ ]:
a.insert(4,77)
print(a)

[7, 2025, 'tiger', 'lion', 77]


In [ ]:
a.append(89)
print(a)

[7, 2025, 'tiger', 'lion', 77, 89]


In [ ]:
a.remove(2025)
print(a)

[7, 'tiger', 'lion', 77, 89]


In [ ]:
a.pop(-3)
print(a)

[7, 'tiger', 77, 89]


In [ ]:
#tuple
b=("apple", "banana", "mango","cherry")
print(b)
print(b[2])
print(len(b))
print(b[1:3])

('apple', 'banana', 'mango', 'cherry')
mango
4
('banana', 'mango')


In [ ]:
#dictionary
person = {



"name": "Alice",

"age": 30,

"city": "New York"
}

print(person ["name"])
print(person.get("age"))
print(person.keys())
print(person.values())

Alice
30
dict_keys(['name', 'age', 'city'])
dict_values(['Alice', 30, 'New York'])


task 2

In [ ]:
j=1
while j<=40:
  print(j)
  j+=1

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40


In [ ]:
#2 PRINT ONLY THE ODD NUMBERS IN 1 TO 40 NUM USING WHILE LOOP
j=1
while j<=40:
  print(j)
  j+=2

1
3
5
7
9
11
13
15
17
19
21
23
25
27
29
31
33
35
37
39


In [ ]:
#3 PRINT EVEN NUMBERS IN 1 TO 40 NUM USING WHILE LOOP
j=0
while j<=40:
  print(j)
  j+=2

0
2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40


In [ ]:
#4 PRINT THE NUMBERS IN THE REVERSE ORDER FROM 1 TO 40 USING WHILE LOOP
i=40
while i>=1:
  print(i)
  i-=1

40
39
38
37
36
35
34
33
32
31
30
29
28
27
26
25
24
23
22
21
20
19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1


In [ ]:
#5 GET I/P FROM USER AND FIND THE FACTORAIL FOR THE NUMBER USING WHILE LOOP
num=int(input("enter a number :"))
fact=1
i=1
while i<=num:
  fact=fact*i
  i+=1
print("Factorial of",num, "is",fact)

enter a number :13
Factorial of 13 is 6227020800


In [ ]:
#6 SUM FO NUMBERS USING LOOP(IF THE NUMBER IS 5 ADD FROM 1 TO 5)
num=int(input("enter a number :"))
s=0
i=1
while i<=num:
  s=s+i
  i+=1
print("sum of",num, "is",s)

enter a number :5
sum of 5 is 15


In [ ]:
#7 USING WHILE LOOP FIND THE FACTORS OF THE GIVEN NUMBER
num = int(input("Enter a number: "))

i = 1

print("Factors of", num, "are:")

while i <= num:
    if num % i == 0:
        print(i)
    i += 1

Enter a number: 9
Factors of 9 are:
1
3
9


task 3

In [ ]:
import numpy as np
arr=[12,34,56,78,99]
print(np.array(arr))
arr1=[1,2,3,4,5]
print(np.array(arr)+np.array(arr1))
a=[12,34,56,78,99,6,7,8]
j=np.array(a).reshape(2,4)
print(j)
print(j.transpose())
print(j.ndim)
b=[12,34,56,78,99,6,7,8]
n=b.copy()
m=np.ones((3,3))
print(a)
n=np.zeros((4,4))
print(b)
c=np.eye(3)
print(c)
d=np.full((4,4),6)
print(d)
e=np.arange(0,8,2)
print(e)
f=np.linspace(0,10,9)
print(f)
o=np.array([1,2,3])
p=np.array([[1,2,3],[4,5,6],[7,8,9]])
t=np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(o.ndim)
print(p.ndim)
print(t.ndim)
u=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(u[0][0])
u=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(u[1,1])
u=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(u[2:,1:])
s=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(s.flatten())
w=np.array([6,7,8])
l=np.array([4,5,6])
print("add:",w + l)
print("multi:",w*l)
i=np.array([[1,7,9],[5,8,6]])
print("sum:",np.sum(i))
print("mean:",np.mean(i))
print("max:",np.max(i))
print("min:",np.min(i))
print("axis 0 sum:",np.sum(i, axis=0))
print("axis 1 sum:",np.sum(i, axis=1))
print(np.random.randint(1,50,300))

[12 34 56 78 99]
[ 13  36  59  82 104]
[[12 34 56 78]
 [99  6  7  8]]
[[12 99]
 [34  6]
 [56  7]
 [78  8]]
2
[12, 34, 56, 78, 99, 6, 7, 8]
[12, 34, 56, 78, 99, 6, 7, 8]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]
[0 2 4 6]
[ 0.    1.25  2.5   3.75  5.    6.25  7.5   8.75 10.  ]
1
2
3
1
5
[[8 9]]
[1 2 3 4 5 6 7 8 9]
add: [10 12 14]
multi: [24 35 48]
sum: 36
mean: 6.0
max: 9
min: 1
axis 0 sum: [ 6 15 15]
axis 1 sum: [17 19]
[36  7 22 10 44 37 16 46 26 31  7  6  3 24 41 22 17 25  1 39 49 43 24  8
 49 42 31 49 44  6 37  4 10 13 38  2  5 12 27 12  6 39 24 17 34 26  2 31
 15 39 34 13 15  5 25 18 23 27 43 34  2 32 15 36  8 48 30 11 22 44 42 48
 45 23 41 38 19 36 37 15  8 12 47  8 32 28 47  6 43 29 48 17 12 16  3 15
 41  7 38 16 11  3  4 32 49  9 16  1  5 48 27 24 44 44  1 32 34 25  5 48
  9 19 12  8 37 21  7 47 48 34  4  5 15 34 15 21  3 48 34 45 10 43  9  9
 34 10  1 25 46 29 44 33  7  5 40 48 28  9 23 40 47 14 45  8 26 48 35  6
 22 20 34 25 26 35 30 23 

task 4

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [ ]:
X=np.array([1000,1200,1500,1800,2000]).reshape(-1,1)
print(X)

[[1000]
 [1200]
 [1500]
 [1800]
 [2000]]


In [ ]:
y = np.array([150, 180, 210, 250, 270]) # Target (Price)

print(y)

[150 180 210 250 270]


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(X_train)

[[2000]
 [1500]
 [1000]
 [1800]]


In [ ]:
print(y_train)
print(y_test)

[270 210 150 250]
[180]


In [ ]:
model = LinearRegression()

# Create model

In [ ]:
y_pred = model.predict(X_test) # Predict on test data
print(y_pred)

NotFittedError: This LinearRegression instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [ ]:
mse = mean_squared_error(y_test, y_pred)
print(mse)

NameError: name 'y_pred' is not defined

In [ ]:
print(f"Mean Squared Error: {mse:.2f}")

NameError: name 'mse' is not defined

In [ ]:
#scikit     libarary for machine learning
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression       #LinearRegression is an algorithm ,linear_model is a model name
from sklearn.metrics import mean_squared_error
#sample dataset: house size (sq ft)vs Price($1000s)
x=np.array([1000,1200,1500,1800,2000]).reshape(-1,1)
print(x)
y=np.array([150,180,210,250,270])     #target (price)
print(y)
#z=np.array([0,1,1,0,1])
#print(z)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
print(x_train)
print(y_train)
print(y_test)
model=LinearRegression()       #create model
model.fit(x_train,y_train)      # train model

[[1000]
 [1200]
 [1500]
 [1800]
 [2000]]
[150 180 210 250 270]
[[2000]
 [1500]
 [1000]
 [1800]]
[270 210 150 250]
[180]


LinearRegression()